### ISSUE TITLE
WARNING auf der Temine Seite

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/sked#104]
`Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: htmlParseEntityRef: expecting ';' in Entity, line: 171 in /Users/abc/Sites/abc/redaxo/src/addons/sked/pages/entries.php on line 482`

**Comment by olien** [comment]
Hm. Kann ich nicht mehr nachvollziehen. Ich mache es vorerst mal zu...

**Comment by alexplusde** [comment]
Ich kanns nachvollziehen:
```
Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: htmlParseEntityRef: expecting ';' in Entity, line: 163 in /home/.../redaxo/src/addons/sked/pages/entries.php on line 482
```

Bei Termin editieren, wenn man custom fields verwendet.

entries.yml

```
langfields:
  - panel: 'images'
    label_de: 'Sprachbezogene Bildelemente'
    label_en: 'Language-related images elements'
    fields:
      - name: 'lang_image'
        type: 'media'
        label_de: 'Bild'
        label_en: 'Image'
      - name: 'lang_images'
        type: 'medialist'
        label_de: 'Bilder'
        label_en: 'Images'

fields:
  - name: 'link'
    type: 'link'
    label_de: 'Interner Link'
    label_en: 'local link'
  - name: 'exlink'
    type: 'text'
    label_de: 'Externer Link'
    label_en: 'global link'
```
