### ISSUE TITLE
custom definition - type: link / Warning: DOMDocument::loadHTML()

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/sked#127]
HI,
habe soeben die custom definitons ausprobiert und wollte ein linkfield an die entries ranhängen. Jeoch wirfts mir dadurch einen Fehler (Warning):

custom_entries.yml:
```
fields:
  - panel: 'images'
    label_de: 'Sprachbezogene Bildelemente'
    label_en: 'Language-related images elements'
    fields:
      - name: 'lang_image'
        type: 'media'
        label_de: 'Bild'
        label_en: 'Image'
      - name: 'lang_images'
        type: 'medialist'
        label_de: 'Bilder'
        label_en: 'Images'

fields:
  - name: 'image'
    type: 'media'
    label_de: 'Bildelement'
    label_en: 'Image element'
  - name: 'file'
    type: 'media'
    label_de: 'Datei Anhang'
    label_en: 'File attachment'
  - name: 'article'
    type: 'link'
    label_de: 'foo'
    label_en: 'blubb'
```

```
Warning: DOMDocument::loadHTML() [<a href='https://php.net/manual/domdocument.loadhtml'>domdocument.loadhtml</a>]: htmlParseEntityRef: expecting ';' in Entity, line: 179 in redaxo/src/addons/sked/pages/entries.php on line 482

Warning: DOMDocument::loadHTML() [<a href='https://php.net/manual/domdocument.loadhtml'>domdocument.loadhtml</a>]: htmlParseEntityRef: expecting ';' in Entity, line: 179 in redaxo/src/addons/sked/pages/entries.php on line 482

```
