### ISSUE TITLE
Abruf: Custom Felder nicht im Ergebnis

### ISSUE THREAD

**Issue by helpy** [FriendsOfREDAXO/sked#45]
Ich habe eine custom_entries.yml angelegt mit folgendem Inhalt:
```
fields:
  - name: 'detail_link'
    type: 'link'
    label_de: 'Link zu Details'
    label_en: 'Link to details'
```
Dieses Feld wird nicht im Editor angezeigt!
Die Feldtypen text, textarea, media und medialist funktionieren.
link und linklist werden nicht angezeigt.
