### ISSUE TITLE
IDEE: Plugin für Tasks

### ISSUE THREAD

**Issue by elpschulzo** [FriendsOfREDAXO/sked#73]
Ich bearbeite gerade ein Kundenprojekt, bei dem Sked eine zentrale Rolle spielt. Kern des Projektes ist die Verwaltung von Datensätzen im Backend (YForm Tables) in Verbindung mit Terminen - und auch Aufgaben.

Anforderung ist auch, dass ein eingeloggter Nutzer anstehende und v.a. verpasste Aufgaben sofort nach dem Login sehen. Es geht konkret um z.B. das Anrufen eines in den YForm Tables administrierten Unternehmens.

In den Kalendern von Google, Outlook und Co. gibt es noch Aufgaben/Tasks, was im Grunde dasselbe wie ein Termin ist nur eben mit dem Zusatz, dass man es als "erledigt" markieren kann.
Genau das würde ich als z.B. Plugin für Sked sehr toll finden. Idealerweise mit den o.g. Zusatzfeatures.

---

Weil ich das im aktuellen Projekt schon alles umgesetzt habe, will ich das hier gleich mal reinpusten. Evtl. dient es als Inspiration oder kann in Schnipseln weiterverwendet werden.

1. Custom Entry für das setzen des "erledigt"-Status:
```
  - name: 'done'
    type: 'checkbox'
    label_de: ''
    options: { 1:erledigt }
```

2. Custom Entry für die Auswahl des zuständigen BE-User:
```
  - name: 'related_user'
    column: 1
    type: 'selectsql'
    label_de: 'betrifft Benutzer'
    qry: "SELECT 0 AS id, '- ohne -' AS name UNION SELECT id, name FROM rex_user WHERE admin = 0 ORDER BY name ASC"
    attribute:
      data-live-search: 'true'
      class: 'selectpicker'
```

3. Mit dem XOutputFilter habe ich in den Header Quellcode eingeschleust, der je nach Anzahl und Typisierung der Termine/Aufgaben folgendermaßen aussehen kann:

![overview_no_tasks](https://user-images.githubusercontent.com/7023022/38867089-508f4656-4243-11e8-8e15-8b00829126a9.PNG)
_Keine Aufgaben/Termine, alles erledigt_

![overview_tasks](https://user-images.githubusercontent.com/7023022/38867113-5fec04d6-4243-11e8-9091-99fb9c2837e6.PNG)
_Wenn Aufgaben/Termine, dann in 3 Kategorien eingeteilt: überfällig, normal (kommend), erledigt (mit Zeiteinschränkung - 2 Wochen und in Zukunft gelegen)_

![overview_tasks_open](https://user-images.githubusercontent.com/7023022/38867159-82c2d2b4-4243-11e8-9169-491292682327.PNG)
_Klick auf das Panel mit Aufgaben öffnet die Liste mit der Möglichkeit, direkt zum Termin zu springen_

![overview_tasks_open_category_hover](https://user-images.githubusercontent.com/7023022/38867192-96ddaf3a-4243-11e8-96a2-057250aa1ea4.PNG)
_Kategorie-Hinweis bei Hover über 1. Zelle_
